repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: script/run-in-env.sh ruff check --fix --exit-non-zero-on-fix --config pyproject.toml
        language: script
        types_or: [python, pyi]
      - id: ruff-format
        name: ruff-format
        entry: script/run-in-env.sh ruff format --config pyproject.toml
        language: script
        types_or: [python, pyi]
      - id: codespell
        name: codespell
        entry: script/run-in-env.sh codespell --toml pyproject.toml
        language: script
        types: [text]
      - id: mypy
        name: mypy
        entry: script/run-in-env.sh mypy
        language: script
        types_or: [python, pyi]
        exclude: ^tests/
